config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'user#index'

  get 'user/show'

  get 'user/about'
  post 'user/about', to: 'user#sign_in'

  get 'user/sign_out'

  get 'user/register_new'
  post 'user/register_new', to: 'user#create'

  get 'user/profile'

  get 'user/:id/edit', to: 'user#edit', as: 'user_edit'
  put 'user/:id', to: 'user#update'

  get 'user/user_login'

  get 'user/about'
  post 'user/about'

  get 'course/index'
  get 'course/new'
  post 'course/new', to: 'course#create'
  get 'course/show'

  get 'course/:id/edit', to: 'course#edit', as: 'course_edit'
  put 'course/:id', to: 'course#update'

  delete 'course/:id', to: 'course#destroy', as: 'course_delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	validates :name, uniqueness: true, :presence => true
	#has_and_belongs_to_many :users
	#mount_uploader :image, ImageUploader
	mount_uploaders :images, ImageUploader
	serialize :images, JSON
	#attr_accessible :image
end

app/models/user.rb
class User < ApplicationRecord
    validates :User_name, uniqueness: true, :presence => true
    validates_format_of :Email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates :Password, :presence => true,
              :confirmation => true,
              :length => {:within => 6..8}
    validates_confirmation_of :Password     
    validates :Mobile_number,
              :numericality => {only_integer: true },
              :length => { is: 10 }
    validates :Gender, 
              :numericality => false
    validates :Confirm_password,:presence => true
    

    has_and_belongs_to_many :courses, -> { distinct }

    validates_associated :courses
    #validates_uniqueness_of :course
    #validates :courses, presence: true, uniqueness:true

    has_attached_file :photo, styles: { large:"600x600", medium: "300x300>", thumb: "100x100>" }
    #validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
    #validates_attachment :photo, presence: true, content_type: { content_type: "image/jpeg" }, size: { in: 0..10.kilobytes }
    validates_attachment :photo, :content_type => { :content_type => /image/, :message => "photo must be an image" }, :size => { :in => 0..10.kilobytes, :message => "photo must be less than 10 kilobytes in size" }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  def new
    @course = Course.new
  end

  def create
    #@course = Course.find(course_params[:id])
    @course = Course.new(course_params)
    if @course.save


      #@course = Course.find(course_params[:id])
        redirect_to course_show_path(id: @course.id)
      else
        render 'new'
      end
  end

  def edit
    # binding.pry
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to user_index_path(id: params[:id])
    else
      render 'edit'
    end
  end 

  def show
    @course = Course.all
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to course_show_path
  end

  def course_params
    params.require(:course).permit(:id, :name, :description, :start_time, :end_time, :level, :mode =>[], :images =>[])
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    #@user = User.all
  end

  def about
    # @name = params[:User_name]
    # @password = params[:Password]
    # @male = params[:male]
    # @female = params[:female]
  end
    def profile
      if params[:id].present?
        user_id = params[:id]
      else
        user_id = params[:user][:id]
      end
      @user = User.find(user_id)
      #@cc = Course.all
        if @user.present? &&  params[:user].present? && params[:user][:course_ids]
          @user = User.find(params[:user][:id])
          @courses = Course.find(params[:user][:course_ids])
          @user.courses << @courses
          #redirect_to user_profile_path
      end
      @user_courses = @user.courses
      #@courses = Course.find(params[:user][:course_ids])
      #@user.courses<<@courses
    end
  def show
    @name = params[:name]
    @password = params[:Password]
    @email = params[:Email]
    @Gender = params[:Gender]
    @tyype = params[:tyype]
    @hidden = params[:email]
    @hobbies = params[:hobbies]
    @photo = params[:photo]
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_profile_path(id: params[:id])
    else
      
     # @user.errors[:Mobile_number] << "Enter valid number"
     # @user.errors[:photo] << "Invalid photo upload format" if @user.errors[:photo_content_type]
     
      render 'edit'
    end
  end

  def sign_in
    @name = params[:User_name]
    @password = params[:Password]
    @email = params[:Email]
    @Gender = params[:Gender]
    @type = params[:tyype]
    @hidden = params[:email]
    @hobbies = params[:hobbies]
    @photo = params[:photo]

    user = User.find { |u| u.User_name == params[:User_name]}
    if (user.present? && user.Password.eql?(params[:Password]))
      session.clear
      session[:current_user_id] = user.id
        redirect_to user_profile_path(id: user[:id])
      #redirect_to user_profile_path(name: params[:User_name], password: params[:Password], Gender: params[:Gender], tyype: params[:tyype], email: params[:email],hobbies: params[:hobbies])
      #redirect_to user_show_path(name: params[:User_name], password: params[:Password], Gender: params[:Gender], tyype: params[:tyype], email: params[:email],hobbies: params[:hobbies])
    else
     flash[:error] = "Incorrect Password!----Please Enter correct Password"
     render 'about'
    end
    end

  def sign_out
    session.clear
      redirect_to user_about_path
  end
  
  def register_new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
    redirect_to  user_about_path
    else
    render 'register_new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:User_name, :Email, :Password,
     :Confirm_password, :Mobile_number, :Gender, :Address, :photo, :tyype=>[], :hobbies=>[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/course/edit.html.erb
<!-- Type : <%= @course[:name]%><br>
Description : <%= @course[:description]%><br>
Start Time : <%= @course[:start_time]%><br>
End Time : <%= @course[:end_time]%><br>
Difficulty Level : <%= @course[:level]%><br>
Mode : <%= @course[:mode]%> -->
<h1 style="color:#000080">Edit Course</h1>


<%= form_for @course, url: {:controller => :course, action: :update}, html: { method: :put } do |form| %>

<%= form.label :name %><br>
<%= form.text_field :name %><br>

<%= form.label :Image %><br>
<%= form.file_field :image%><br>

<%= form.label :description %><br>
<%= form.text_field :description %><br><br>

<%= form.label :start_time %><br>
<%= form.datetime_select :start_time, :ampm => true %><br>

<%= form.label :end_time %><br>
<%= form.datetime_select :end_time, :ampm => true %><br><br><br>

<%= form.label :difficulty_level %><br>
<%= form.radio_button :level, 'easy' %> easy
<%= form.radio_button :level, 'medium' %> medium
<%= form.radio_button :level, 'hard' %> hard <br><br>

<%= form.label :Mode %><br>
<%= form.check_box :mode, {:multiple => true}, "online",nil %>Online
<%= form.check_box :mode, {:multiple => true}, "offline",nil %>Offline<br><br>

<%= form.submit "Update" %>

<%= link_to 'Back', course_show_path %>

<% end %>

app/views/course/index.html.erb
<h1>Welcome to courses</h1>
<ul>
     <li><%= link_to 'New', course_new_path %></li>
     <li><%= link_to 'show all', course_show_path %></li>
</ul>
<%= link_to 'Back', user_index_path %>

app/views/course/new.html.erb
<h1>New Course</h1>
<%= form_for @course, url: course_new_path, html: { method: :post, :multipart => true } do |form| %>

    <% if @course && @course.errors.any? %>
    <div id="error_explanation">
      <h2>
        prohibited this user from being saved:
      </h2>
    </div>
  <% end %>

    <%= form.label :Name %><span style="color:red"><%=@course.errors.messages[:name].presence.to_s%> </span><br>
	<%= form.text_field :name %><br><br>
    
    <%= form.label :Image %><br>
    <%= form.file_field :images, multiple: true%><br>

    <%= form.label :Mode %><br>
    <%= form.check_box :mode, {:multiple => true}, "online",nil %>Online
    <%= form.check_box :mode, {:multiple => true}, "offline",nil %>Offline

    <br><br>

	<%= form.label :Description %><br>
	<%= form.text_area :description %><br><br>

	<%= form.label :start_time %><br>
	<%= form.datetime_select :start_time, :ampm => true %>
	<br><br>

	<%= form.label :end_time %><br>
	<%= form.datetime_select :end_time, :ampm => true %>
	<br><br>
    
    <%= form.label :difficulty_level %><br>
    <%= form.radio_button :level, 'easy' %> easy
    <%= form.radio_button :level, 'medium' %> medium
    <%= form.radio_button :level, 'hard' %> hard <br><br>
    <p>
    <%= form.submit :submit, class: 'course-submit'%>
	</p>
    <%= link_to 'Back', course_show_path %>
<% end %>

app/views/course/show.html.erb
<h1>Listing courses</h1>
 
<table>
  <tr>
    <th>name</th>
    <th>description</th>
    <th></th>
  </tr>
 
  <% @course.each do |course| %>
    <tr>
      <td><%= course.name %></td>
      <td><%= course.description %></td>
     <!-- <td><%#= course.images.url %></td> -->
      <td><%= link_to 'Update', course_edit_path(id: course[:id])  %></td>
      <td><%= link_to 'Delete', course_delete_path(id: course.id),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <!-- <p>PHOTO<br><%#= image_tag course.image.url.to_s %></p> -->

  <% end %>
  <%= link_to 'Back', course_index_path %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/about.html.erb
<%  content_for :title do %>
About
<% end %>
<h1 style="text-align: center;">Login</h1>
<%= form_tag(controller: "user", action: "sign_in", method: "post") do %>
    <div class="boxlogin">
    <%= label_tag 'User_name' %>
	<%= text_field_tag 'User_name' %><br><br>

    <%= label_tag 'Password' %>
    <%= password_field_tag 'Password'%><br><br>
<!--
    <%= label_tag 'Gender' %>
    <%= radio_button_tag :Gender, 'male' %> male
    <%= radio_button_tag :Gender, 'female' %> female <br>
    <br>

    <%= label_tag 'Type' %>
    <%= radio_button_tag :tyype, 'student' %> student
    <%= radio_button_tag :tyype, 'teacher' %> teacher <br><br>
    
    <%= label_tag 'Hobbies' %><br>
    <%= select_tag "hobbies", "<option>cricket</option><option>football</option><option>cooking</option><option>singing</option><option>dancing</option><option>painting</option>".html_safe, multiple: true%>
    <br> <br>

    op1<input type="checkbox" name="optops_new[]" id="optops_new" value="op1">
    op2 <input type="checkbox" name="optops_new[]" id="optops_news" value="op2">

    <br> <br>

    <%= hidden_field_tag :email, "test@test.com" %>-->

	<%= button_tag 'sign_in' , class: "buttonn" %><br><br>
    </div>
<p style="text-align: center;">
<%= link_to 'Back', user_index_path%>
</p>
<% end %>
<!-- 
<div style="border:1px red solid">
<%= @User_name %><br>
<%= @Password %><br>
<%= @male %>
<%= @female %><br>

</div> -->

app/views/user/current_user.html.erb
<p>Hello, <%= current_user.username %>.</p>

app/views/user/edit.html.erb
<h1 style="color:#000080">Edit User</h1>
<%= form_for @user, url: {:controller => :user, action: :update}, html: { method: :put } do |form| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :User_name %><br>
    <%= form.text_field :User_name %>
  </p>
  <p>
    <%= form.label :Password %><br>
    <%= form.text_field :Password %>
  </p>
  <p>
    <%= form.label :Email %><br><span style="color:red"><%=@user.errors.messages[:Email].presence.to_s%></span>
    <%= form.text_field :Email %>
  </p>
  <p>
    <%= form.label :Mobile_number %><span style="color:red"><%=@user.errors.messages[:Mobile_number].presence.to_s%></span><br>
    <%= form.text_field :Mobile_number %>
  </p>
  <p>
   <%= form.label 'Gender' %>
    <%= form.radio_button :Gender, 'male' %> male
    <%= form.radio_button :Gender, 'female' %> female <br>
  </p>

 <!--  <p>
    <%= form.label 'Type' %><br>
    <%= form.radio_button :tyype, 'student' %> student
    <%= form.radio_button :tyype, 'principle' %>principle
    <%= form.radio_button :tyype, 'teacher' %> teacher <br><br> 
  </p> -->
  
  
  <p>
    <%= form.label 'Type' %><br>
    <%= form.check_box("tyype", {:multiple => true}, "student",nil)%>student
    <%= form.check_box("tyype", {:multiple => true}, "principle",nil)%>principle
    <%= form.check_box("tyype", {:multiple => true}, "teacher",nil)%>teacher
  </p>


  <p>
    <%= form.label 'Hobbies' %><br><br>
    <%= form.select(:hobbies, [['cricket'],['football'],['painting'], ['drawing'], ['playing'], ['singing']],{ :prompt => "Please select"},{ :multiple => true}) %>
  </p>
  <!-- <p>
    <%= form.label :Gender %><br><span style="color:red"><%=@user.errors.messages[:Gender].presence.to_s%> </span>
    <%= form.text_field :Gender %>
  </p> -->

  <p>
    <%= form.label :Address %><br>
    <%= form.text_field :Address %>
  </p>
  
  <%= form.label :photo %><br><span style="color:red"><%=@user.errors.messages[:photo].presence.to_s%></span>
  <%= form.file_field :photo %>
  <%= form.submit "Update" %>
  </p>
<% end %>

app/views/user/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>main</title>
    <style>
    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #333;
    }

    li {
      float: left;
    }

    li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }

    li a:hover {
      background-color: #111;
    }
    </style>

  </head>

  <body>
<ul>
     <li><%= link_to 'Login', user_about_path %></li>
     <li><%= link_to 'Sign up', user_register_new_path %></li>
     <li><%= link_to 'Courses', course_index_path %></li>
</ul>
    <%= yield %>
  </body>
</html>

app/views/user/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>edit</title>
    <style>
    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #333;
    }
    li {
      float: left;
    }
    li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }
    li a:hover {
      background-color: #111;
    }
    </style>

  </head>

  <body>
<ul>
     <li><%= link_to 'User Profile'%></li>
     <li><%= link_to 'Edit_User', user_edit_path(session[:current_user_id]) %></li>
     <li><%= link_to 'sign_out', :controller => :user, :action => :sign_out %></li>
</ul>
<p>User Name : <%= @user[:User_name] %></p>
<p>Email : <%= @user[:Email] %></p>
<p>Password : <%= @user[:Password] %></p>
<p>Number : <%= @user[:Mobile_number]%></p>
<p>Address : <%= @user[:Address]%></p>
<p>Gender : <%= @user[:Gender] %></p>
<p>Type : <%= @user[:tyype]%></p>
<p>Hobbies : <%= @user[:hobbies]%></p>
<p>PHOTO<br><%= image_tag @user.photo.url(:medium) %></p>

<%= form_with model: @user, url: user_profile_path, html: { method: :get } do |form| %>
  <% if @user && @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        prohibited this user from being saved:
      </h2>
    </div>
  <% end %>
  <%= form.hidden_field :id, :value => params[:id]%>
  <%= form.collection_select :course_ids, Course.all, :id, :name %>
  <%= form.submit "add" %>
<% end %>

<h3 style="color:  #556B2F">Courses</h3>
<% @user_courses.each do |c| %>
    Name : <%= c.name %><br>
    Description : <%= c.description %><br><br>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/user/register_new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1 style="color:#000080"><center>Create User</center></h1>
<%= form_for @user, url: user_register_new_path, html: { method: :post } do |form| %>
  <% if @user && @user.errors.any? %>
    <div id="error_explanation">
    </div>
  <% end %>

  <div class="box">
    <p>
    <%= form.label :User_name %><span style="color:red"><%=@user.errors.messages[:User_name].presence.to_s%> </span><br>
    <%= form.text_field :User_name, placeholder: "Enter Name" %>
    </p>

    <p>
    <%= form.label :Email %><span style="color:red"><%=@user.errors.messages[:Email].presence.to_s%> </span><br>
    <%= form.text_field :Email, placeholder: "Enter Email" %>
    </p>

    <p>
    <%= form.label :Password %><span style="color:red"><%=@user.errors.messages[:Password].presence.to_s%> </span><br>
    <%= form.text_field :Password, placeholder: "Enter Password" %>
    </p>

    <p>
    <%= form.label :Confirm_password %><span style="color:red"><%=@user.errors.messages[:Confirm_password].presence.to_s%> </span><br>
    <%= form.text_field :Confirm_password, placeholder: "Confirm Password" %>
    </p>

    <p style = "text-align:center" >
    <%= form.button "Login",class: "button"%>
    </p>
  </div>
  <p style = "text-align:center">
    <%= link_to 'Login', user_about_path %>
    <%= link_to 'Back', user_index_path %>
  </p>
<% end %>
</body>
</html>

app/views/user/show.html.erb
<p>User Name : <%= @name %></p><br>
<p>Password : <%= @password %></p><br>
<p>Gender : <%= @Gender %><br>
<p>Type : <%= @tyype%>
</p><br>
<p>Hidden Email : <%= @hidden %>
<p>Hobbies : <%= @hobbies %></p>
<p>PHOTO<%= @user.photo.url(:medium) %></p>

app/views/user/user_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>login</title>
</head>
<body>
<h1 style="color:#000080">Login</h1>
<%= form_for :user, url: user_sign_in_path, html: { method: :post } do |form| %>

  <div class="container">
      <% flash.each do |key, value| %>
        <div style="color:red" class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  <p>
    <%= form.label :User_name %><br>
    <%= form.text_field :User_name %>
  </p>
 
  <p>
    <%= form.label :Password %><br>
    <%= form.text_field :Password %>
  </p>
  <p>
  <%= form.check_box(:male) %>
  <%= form.label(:male, "male") %>
  <%= form.check_box(:female) %>
  <%= form.label(:female, "female") %>
  </p>
  <p>
    <%= form.button "Login" %>
  </p>
  <%= link_to 'Back', user_index_path %>
<% end %>
</body>
</html>